name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # --- CI: Build y Tests ---
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar tests
        run: npm test

  # --- CD: Deploy en VM ---
  deploy:
    needs: ci # Solo corre si CI pasa
    runs-on: ubuntu-latest
    steps:
      - name: Conectar por SSH y Desplegar
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VM_USERNAME }}/ecommerce-appweb
            git pull origin main
            docker-compose down
            docker-compose up -d --build
            docker image prune -f
